version: 2.1
jobs:
  build:
    docker:
      - image: kauplan/review2.5
    working_directory: /build
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get -y install build-essential ruby-dev
      - run: gem install md2review
      - run: npm i 
      - run: npx textlint review-starter/*.md
      - run: md2review review-starter/chapxx-mr-mo.md > review-starter/chapxx-mr-mo.re
      - run: cd /build/review-starter; rake pdf
      - store_artifacts:
          path: /build/review-starter/Voice_UI_Experts_Project.pdf
          destination: Voice_UI_Experts_Project.pdf
